lab1 done
OMWi/todo-app pull request #1
Opened 2022-04-11 14:18 UTC by OMWi

2022-04-11 14:30 UTC, katetushkan requested changes

2022-04-11 14:30 UTC, katetushkan commented on lab1/client.py
> +class Client:
where is Server?

2022-04-11 15:04 UTC, OMWi commented on lab1/client.py
> +class Client:
Клиент выполняет роль сервера. Один поток проверяет входящие сообщения, второй отправляет

2022-04-12 11:58 UTC, katetushkan commented on lab1/client.py
> +class Client:
`4`.

2022-04-27 11:23 UTC, merged