Lab3
OMWi/todo-app pull request #4
Opened 2022-05-04 11:37 UTC by OMWi

deploy: https://omwi.github.io/

2022-05-08 14:53 UTC, katetushkan requested changes

2022-05-08 14:53 UTC, katetushkan commented on todo-app/html/login.html
> +            <p>Email:</p>
```suggestion
            <label for="...">Email:</label>
```

2022-05-08 14:53 UTC, katetushkan commented on todo-app/html/main.html
> +        }
Can't you use classes for these styles?

2022-05-08 14:53 UTC, katetushkan commented on todo-app/html/main.html
> +            <i onclick="onclickSidemenu()" class="fa-solid fa-bars fa-2xl"></i>
Clickable items should be `buttons or `a`s.

2022-05-08 14:53 UTC, katetushkan commented on todo-app/html/main.html
> +            <div class="logout">
Also `button` probably.

2022-05-08 14:53 UTC, katetushkan commented on todo-app/html/main.html
> +                <p class="create-project-text">Create project</p>
`button`?

2022-05-08 14:53 UTC, katetushkan commented on todo-app/html/main.html
> +                    <header class="task-header">
Second `header` within `section`. This is not correct.

2022-05-08 17:23 UTC, OMWi commented
all fixed

2022-05-11 14:55 UTC, omwi commented
Напишите еще какие функции реализовывать в 4 лабе, пожалуйста

2022-05-16 13:32 UTC, katetushkan commented
- Создание задач, секций, проектов
- Расставление приоритетов задач
- Перемещение задач между секциями
- Поиск

2022-05-16 13:32 UTC, katetushkan approved these changes
<kbd>8</kbd>

2022-05-16 14:08 UTC, merged